version: '3'

services:
  pix-broker:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/pix.json
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
    volumes:
      - ./pix.json:/tmp/pix.json
    command: ['-c=standalone.xml']

  cnav-idp:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/cnav.json
      KEYCLOAK_FRONTEND_URL: http://localhost:8081/auth
    volumes:
      - ./cnav.json:/tmp/cnav.json
    command: ['-c=standalone.xml']
